version: '3.4'

services:
  readingisgood-db:
    image: mongo:5.0.2
    container_name: "readingisgood-db"
    ports:
      - 27018:27017
  readingisgood_denizei_cache:
    image: readingisgood_denizei_cache
    build:
      context: .
      dockerfile: ./Dockerfile_cached
    ports:
      - 8082:8082
    links:
      - readingisgood-db