package com.getir.readingisgood.domain;

public enum ChangeLogActionType {
    ORDER_INSERT, BOOK_INSERT, ORDER_UPDATE,
    BOOK_UPDATE_BY_USER, BOOK_UPDATE_BY_ORDER, CUSTOMER_CREATED, MONTLY_REPORT_FETCHED, COMMON_LOG
}
